# Generated by Django 5.0.14 on 2025-09-30 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prefecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                ("state", models.CharField(max_length=2, verbose_name="Estado")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prefeitura",
                "verbose_name_plural": "Prefeituras",
                "db_table": "prefectures",
                "indexes": [
                    models.Index(fields=["cnpj"], name="prefectures_cnpj_8e8496_idx"),
                    models.Index(
                        fields=["is_active"], name="prefectures_is_acti_d5ce71_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("upa", "UPA"),
                            ("hospital", "Hospital"),
                            ("posto", "Posto de Saúde"),
                            ("especializado", "Centro Especializado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Unidade",
                    ),
                ),
                (
                    "cnes",
                    models.CharField(
                        help_text="Código Nacional de Estabelecimento de Saúde",
                        max_length=20,
                        unique=True,
                        verbose_name="CNES",
                    ),
                ),
                ("address", models.TextField(verbose_name="Endereço")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prefecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_units",
                        to="prefecture.prefecture",
                        verbose_name="Prefeitura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade de Saúde",
                "verbose_name_plural": "Unidades de Saúde",
                "db_table": "health_units",
                "indexes": [
                    models.Index(
                        fields=["prefecture", "unit_type"],
                        name="health_unit_prefect_5e74f0_idx",
                    ),
                    models.Index(fields=["cnes"], name="health_unit_cnes_250c3a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                ("crm", models.CharField(max_length=20, verbose_name="CRM")),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "specialties",
                    models.JSONField(
                        default=list,
                        help_text='Lista de especialidades. Ex: ["Clínica Geral", "Pediatria"]',
                        verbose_name="Especialidades",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Conta de usuário para médicos que acessam o sistema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário no Sistema",
                    ),
                ),
                (
                    "prefecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="prefecture.prefecture",
                        verbose_name="Prefeitura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Médico",
                "verbose_name_plural": "Médicos",
                "db_table": "doctors",
                "indexes": [
                    models.Index(
                        fields=["prefecture", "is_active"],
                        name="doctors_prefect_2c8a67_idx",
                    ),
                    models.Index(fields=["cpf"], name="doctors_cpf_89af9c_idx"),
                    models.Index(fields=["crm"], name="doctors_crm_0b01cc_idx"),
                ],
                "unique_together": {("crm", "prefecture")},
            },
        ),
        migrations.CreateModel(
            name="PrefectureStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("operator", "Operador"),
                            ("viewer", "Visualizador"),
                        ],
                        default="viewer",
                        help_text="Define as permissões administrativas no sistema da prefeitura",
                        max_length=20,
                        verbose_name="Papel Administrativo",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Secretaria de Saúde, Coordenação de UPAs, etc.",
                        max_length=100,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "prefecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="prefecture.prefecture",
                        verbose_name="Prefeitura",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuário do sistema vinculado a este perfil administrativo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefecture_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário da Prefeitura",
                "verbose_name_plural": "Funcionários da Prefeitura",
                "db_table": "prefecture_staff",
                "indexes": [
                    models.Index(
                        fields=["prefecture", "user"],
                        name="prefecture__prefect_3bbcf2_idx",
                    ),
                    models.Index(fields=["role"], name="prefecture__role_de78b2_idx"),
                ],
                "unique_together": {("user", "prefecture")},
            },
        ),
    ]
